### ISSUE TITLE
Adjustable frame skip in IR

### ISSUE THREAD

**Issue by nichwall** [FINISinstrument/FINIS-Console#12]
In order to reduce disk and CPU usage, only every N frames are saved in the IR camera (changed from 1 to 10 during flight tests). This value should be modifiable during runtime in order to help with debugging and actual tests. The number of frames skipped will also be written to the log file.

**Comment by FINISinstrument** [comment]
d78fa76d24ce5576d50a54399fb00d6ce0c6fe35
