### ISSUE TITLE
Context framerate control

### ISSUE THREAD

**Issue by nichwall** [FINISinstrument/FINIS-Console#9]
Testing needs to be completed on the CPU usage when the context camera and A-band camera are controlled either in lock step with the IR camera vs just letting them run until signaled to stop recording.
The lock step seemed to reduce CPU usage in the past, but can lead to dropped frames and will not be reliable when the IR camera is being run at different framerates.
If the CPU usage is determined to be similar, then remove the lockstep with the main IR camera.

**Comment by FINISinstrument** [comment]
CPU usage is similar, so framerate of the context and A-band camera is now controlled by the individual cameras
